ALTER TABLE "RawMaterial" ADD COLUMN "length" TEXT NOT NULL DEFAULT '';
ALTER TABLE "RawMaterial" ADD COLUMN "width" TEXT NOT NULL DEFAULT '';
ALTER TABLE "RawMaterial" ADD COLUMN "height" TEXT NOT NULL DEFAULT '';
